[tool.poetry]
name = "progrespine"
version = "0.1.0"
description = "ProgreSpine Project"
authors = ["Roozbeh Bazargani <roozbehbazargani@gmail.com>"]
readme = "README.md"
packages = [{ include = "progrespine" }]

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
numpy = "^2.4.5"
torch = "2.10.0"
simpleitk = "^2.5.2"
lightning = "^2.5.5"
pyarrow = "17.0.0"
mlflow = "^3.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
